services:
  mysql:
    image: mysql:8.0
    container_name: mysqldb

    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mysqldb
      MYSQL_USER: user
      MYSQL_PASSWORD: password

    ports:
      - "3307:3306"

    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql/init:/docker-entrypoint-initdb.d

volumes:
  mysql_data: